### ISSUE TITLE
Giving due credit

### ISSUE THREAD

**Issue by vnherdeiro** [ValJ10/TMS#1]
Valondine Jeudy,

I see that this repository is mostly a copy of my code, and you know which project I am referring to. Let me remind you that I helped twice with understanding this code, hence it is quite a displeasant surprise to see that you are advertising it in your portfolio without giving me any credit. Github is about sharing code, but considering the few modifications you made the correct behaviour would have been to fork my project, or at least to mention how much you are using from it in your README.md .

This is a serious misconduct. I will involve moderation if no action is taken on your side in the next few days.

**Comment by ValJ10** [comment]
I understand, I was in rush. Sorry.
